### ISSUE TITLE
Use yarn instead of "npm install" to install your node_modules

### ISSUE THREAD

**Issue by nandesu** [GeekyAnts/native-base-cli#2]
Your init.js is using npm install, instead of yarn to install the node_modules. 
This is causing the following issue: 
https://github.com/GeekyAnts/native-base-boilerplate/issues/2

Kind regards.

**Comment by sankhadeeproy007** [comment]
Thanks for pointing it out. Will be fixed very soon.

**Comment by shivrajkumar** [comment]
@nandesu Yarn has been added now
